name: Tagger
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
jobs:
  Do-Something:
    runs-on: ubuntu-latest
    steps:
      - name: Create IMAGE_TAG from GitHub SHA
        if: github.ref == 'refs/heads/master'
        run: |
          echo "IMAGE_TAG=`git rev-parse --short HEAD`" >> $GITHUB_ENV

      - name: Create IMAGE_TAG from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Echo Image tag
        run: echo ${{ env.IMAGE_TAG }}
